---
title: "Aid analysis"
date: last-modified
format:
  html:
    toc: true
    toc-location: right
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(here)
library(cowplot)

plotSave <- function(name, chart) {
    ggsave(filename = here('plots', paste0({{ name }}, '.jpeg')),
        plot   = {{ chart }},
        width  = 11,
        height = 6)
}

```

```{r}

aid <- read.csv(here('data_raw','World Wide Aid.csv'))

aid1 <- aid %>% 
    filter(Type.of.Aid.General == "Military") %>% 
    select(Countries, Original.Currency,Type.of.Aid.General, Monetary.Value.as.Given.by.Source, Total, Converted.Value.in.EUR, Total.monetary.value.delivered.in.EUR, Total_in_USD) %>% 
    filter(Total != "") %>% 
    filter(Total != ".") %>% 
    group_by(Countries) %>% 
    mutate(Total_in_USD = as.double(Total_in_USD)) %>% 
    mutate(Total_by_Country = sum(Total_in_USD)) %>% 
    ungroup()
head(aid1)

aid2 <- aid1 %>% 
    select(Countries, Total_by_Country) %>% 
    slice(1, 13, 14,28,31,56,63,91,103,113,125,131,145,149,150,157,161,165,170,189,196,206,213,221,227,237,240,242,254,258,271,284,299,307)
head(aid2)

aid2_plot <- aid2 %>% 
    mutate(Total_by_Country = Total_by_Country / 10^9) %>% 
    mutate(Countries = fct_reorder(Countries, Total_by_Country)) %>% 
    ggplot()+
    geom_col(aes(x = Total_by_Country, y = Countries)) +
    labs(x = "Total Military Aid (Billions of $)", y = "", title = "Foreign Military Aid to Ukraine")+
    theme_bw()+
    scale_x_continuous(expand = expansion(mult = c(0, 0.05)))
aid2_plot

```

```{r}
#| eval: false
#| include: false

plotSave('aid2_plot', aid2_plot)
    
```
