---
title: "Walkability and Health"
subtitle: "How the Walkability of US Cities Affects the Health of Its Citizens"
author: "Bogdan Bunea, Ian Milko, Collin Schwab, and Rayyan Hussien"
date: September 24, 2023 
format: 
  html:
    toc: true 
    toc-location: right
    theme: flatly
    self-contained: true
---

```{r}
#| label: setup 
#| include: false

# Load libraries and settings here
library(tidyverse)
library(here)

knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = "figs/", # Folder where rendered plots are saved
  fig.width = 7.252, # Default plot width
  fig.height = 4, # Default plot height
  fig.retina = 3 # For better plot resolution
)

# Put any other "global" settings here, e.g. a ggplot theme:
theme_set(theme_bw(base_size = 20))

# Write code below here to load any data used in project
russia_losses_equipment<- read_csv(here('data_raw', 'russia_losses_equipment.csv'))
russia_losses_personnel<- read_csv(here('data_raw', 'russia_losses_personnel.csv'))

p <- russia_losses_equipment %>%
    ggplot() +
    geom_point(aes(x = day, y = APC))
p

p1 <- russia_losses_personnel %>%
    ggplot() +
    geom_point(aes(x = day, y = personnel))
p1

```


## Research Question

What, if any, correlation exists between the amount of foreign military aid to Ukraine and military personnel and equipment losses for both sides?

Through this question, we aim to show if a foreign military aid to Ukraine has had an impact on their ability to destroy the enemy, and if there is, is that newfound ability significant enough to give them an advantage in the war.


## Data Sources

1. 2022 Russia-Ukraine War

   <https://github.com/leedrake5/Russia-Ukraine/graphs/commit-activity>

   This dataset, found on GitHub, is an adaptation of 

## Anticipated Results

Two possible variables can be a Walk ability Score and Health Outcomes.

**1.** Walk ability Score: This variable would measure the walkability of various U.S. cities, potentially on a scale ranging from 0 to 100 (could change), and the higher the score is, the greater the walkability in that city is. The distribution across cities could potentially follow a unimodal distribution, where most cities would be in the middle range and a few have very low or very high scores.

**2.** Health Outocomes: This variable would include diverse health measures, including factors like obesity rates, diabetes prevalence, and mental health scores, all combined for each city. The distribution of health outcomes could potentially be multimodal. Some cities may experience low health issues, while others could experience high rates of health issues. Therefore, we would expect cluster of cities sharing similar health outcomes, leading to several peaks in the distribution.


Relationship between variables:

**1.** Walkability Score and Physical Activity: We expect there to be a positive correlation between these two variables. Since, cities with a higher walkability score (cities that have easier access to walking, biking, or even public transportation), would help encourage higher levels of physical activity. So, we might find a positive correlation between the Walkability Score and Physical Activity, meaning that the as the walkability score increases, the physical activity levels are expected to increase.

**2.** Walkability Score and Health Issues: We expect there to be a negative correlation between these two variables. Thus, cities with a higher walkability score might have a lower rates of health issues. That's since, citites with a higher walkability score would encourage the people to be more physically active. Also, as the walkability score increases, the health issues rates decreases.


Two Charts:

**1.** A scatterplot comparing walkability scores and physical activity levels in different U.S. cities could be valuable for visualizing the degree of correlation between these variables. This chart would help assess whether cities with higher walkability scores tend to have increased physical activity.

**2.** A bar chart contrasting walkability score categories (e.g., Low, Moderate, High) with obesity rates/health issues in different U.S. cities could provide a clear visual representation of the relationship between walkability and obesity/health issues. This chart would enable us to examine if cities with better walkability scores tend to have lower obesity rates/ health issues among residents.


Expected correlations between chosen variables guide the research question and analysis. These hypotheses shape the research focus and potential findings.

**1.** Expecting a positive link between walkability scores and physical activity levels suggests that pedestrian-friendly cities may encourage more exercise, impacting urban planning and health strategies. 

**2.** Expecting a negative connection between walkability scores and obesity rates/health issues highlights the role of walkability in addressing public health issues.


ALL MEMBERS CONTRIBITED EQUALLY 


